# Generated by Django 2.1.5 on 2019-01-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicType',
            new_name='Resources',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='topictype',
            new_name='resources',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='typedescription',
            new_name='resourcedescription',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='typename',
            new_name='resourcename',
        ),
        migrations.AlterModelTable(
            name='resources',
            table='resources',
        ),
    ]
